### ISSUE TITLE
Site can't import

### ISSUE THREAD

**Issue by Hillgrove** [max-arias/poe-gems-downloader#2]
is the project dead like the gazillion other POE tools?

**Comment by max-arias** [comment]
Hey, I'm not playing this league, but what's up?

**Comment by Hillgrove** [comment]
Havn't played myself this league either, but I just saw your site in the consolidated poe-tools list and thought I'd try it out.

tried to import this script:

https://pastebin.com/ssLBbZ66

(works in POB), but it says:

"There was an error processing the build, please leave a bug report by clicking: Here"

**Comment by max-arias** [comment]
Oh, cool cool. I'll take a look, probably during the weekend. 

Thanks for the report. 👍
